### ISSUE TITLE
Helm3 CRD Support 

### ISSUE THREAD

**Issue by kri5** [Orange-OpenSource/casskop#132]
Helm v2 has now reached its latest release, and ongoing development is going toward Helm v3.

Some changes happened between v2 and v3, such as there is no more `crd-install` hook, but now CRD should live in its own top-level directory named `crd`, and everything inside it would be installed before rendering templates.

What would be the proper was to support both worlds? Duplicating CRDs (one definition living in `crd` directory and the other one using `crd-install` hook, leading to a warning with helmv3, but should still be working)?

**Comment by kri5** [comment]
It seems necessary to change `apiVersion` to `v2` in the Chart.yaml, which means breaking compatibility with Helm 2, and that might not be what is wanted as of now.

**Comment by cscetbon** [comment]
we've removed any reference to helm2 and use only helm3
