### ISSUE TITLE
Add example for node tolerations

### ISSUE THREAD

**Issue by Jabbl** [Orange-OpenSource/casskop#148]
In #138 it looks like support for tolerations were added. However, I can find no documentation on how to add them to the `cassandra-cluster.yaml`.

Would it be possible to provide an example on how to define tolerations, and explain whether they are global, dc-specific or rack-specific?

**Comment by fdehay** [comment]
Hello @Jabbl, sorry for the (very long) delay. We're taking your request in our current sprint.
You can see what is going on in the Auto-Kanban: https://github.com/Orange-OpenSource/casskop/projects/1

**Comment by fdehay** [comment]
Done in https://github.com/Orange-OpenSource/casskop/pull/177
