### ISSUE TITLE
Eviction and leadership

### ISSUE THREAD

**Issue by fdehay** [Orange-OpenSource/casskop#176]
When Casskop's pod is evicted by K8S for resource shortage, the pod stays in Evicted mode.
When a new pod is spawned by K8S once some resources have been freed, ne new pod does not start.
Workaround is to delete the evicted pod so that the new pod starts correctly.

**Comment by erdrix** [comment]
To add some precisions, if we scale the operator deployment : 

```sh
$ kubectl scale deployment.v1.apps/casskop-demo-cassandra-operator --replicas=2
```

We will have the following status : 

```sh
$ kubectl get pods 
casskop-demo-cassandra-operator-6bd66b76dd-vtqvj       0/1     Running   0          25m
casskop-demo-cassandra-operator-6bd66b76dd-xt77t       1/1     Running   0          21h
```

With the following error : 

```sh
$ kubectl describe pods casskop-demo-cassandra-operator-6bd66b76dd-vtqvj 
Warning  Unhealthy  25m                  kubelet, node005   Readiness probe failed: time="2020-01-28T10:08:57Z" level=info msg="error file don't exists : stat /tmp/operator-sdk-ready: no such file or directory"
Warning  Unhealthy  25m                  kubelet, node005   Readiness probe failed: time="2020-01-28T10:09:07Z" level=info msg="error file don't exists : stat /tmp/operator-sdk-ready: no such file or directory"
```

I think we should have a look on leader election using operator-sdk : https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/leader-for-life.md 

> Operators need leader election to ensure that if the same operator is running in two separate pods within the same namespace, only one of them will be active. The primary goal of leader election is to avoid contention between multiple active operators of the same type.

**Comment by allamand** [comment]
I think the leader election is already implemented that that my be the root cause to the pod not be ready, I think only the leader may be allow to write the ready file..

**Comment by erdrix** [comment]
My bad,  it's for multi-casskop that isn't implemented :/.
So we need to manage the case where a pod is in an evicted state : https://docs.openshift.com/container-platform/4.1/applications/operator_sdk/osdk-leader-election.html#osdk-leader-with-lease-election_osdk-leader-election

But somethings is weird, because the evicted one should be recreated after beeing evicted during 5 min, refering to the documentation and cluster `pod-eviction-timeout` configuration (or did I miss something else :/ ?) : 

```sh
$ kubectl describe pod casskop-demo-cassandra-operator-6bd66b76dd-xt77t | grep -i toleration -A 2 
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

**Comment by fdehay** [comment]
CLosing this at it did not re occur.
