### ISSUE TITLE
Custom C* image requirements for CassKop

### ISSUE THREAD

**Issue by fdehay** [Orange-OpenSource/casskop#180]
By default, CassKop is compatible with the official C* image.
Some users may want to use a custom image for their purpose.

We need to describe what is expected from that custom image as our bootstrap mechanism is changing it as if it were the official C* image.

In particular, we need to explain:
- how to use a different jvm
- how to specify a different GC
- how to specify a specific liveness probe
- how to change the readyness timeout

This should be in the documentation and possibly in the tests

**Comment by berln** [comment]
I would add :
How to change the readyness failureThreshold:
 
This parameter would take into account a long Cassandra startup after a crash.
I usually increase it when the pod takes more than the default 4 minute to be ready.

**Comment by cscetbon** [comment]
Fixed in 0.5.1, see this [README](https://github.com/Orange-OpenSource/casskop/tree/master/docker/bootstrap/README.md#cassandra-bootsrap-image-for-casskop)
