### ISSUE TITLE
Allow to modify liveness and readiness probes

### ISSUE THREAD

**Issue by cscetbon** [Orange-OpenSource/casskop#183]
Probes are automatically defined and configure to use 
- https://github.com/Orange-OpenSource/casskop/blob/v0.5.0-release/docker/bootstrap/files/liveness-probe.sh
- https://github.com/Orange-OpenSource/casskop/blob/v0.5.0-release/docker/bootstrap/files/ready-probe.sh. 

Parameters are also hardcoded https://github.com/Orange-OpenSource/casskop/blob/v0.5.0-release/pkg/controller/cassandracluster/generator.go#L52-L58.

All this should be made configurable

**Comment by cscetbon** [comment]
PR to implement it #184

**Comment by erdrix** [comment]
Are the PR https://github.com/Orange-OpenSource/casskop/pull/201 and PR https://github.com/Orange-OpenSource/casskop/pull/206 enough to close this issue ?

**Comment by cscetbon** [comment]
I think so. Closing it
