### ISSUE TITLE
Centralize information information between code and tests

### ISSUE THREAD

**Issue by cscetbon** [Orange-OpenSource/casskop#186]
Volumes mounts are used in Casskop source code as in dgoss scripts :

https://github.com/Orange-OpenSource/casskop/blob/f59dbb9aeb316ee3a937d250367e5d2eb5b2f09e/docker/bootstrap/dgoss/util.sh#L134-L135

https://github.com/Orange-OpenSource/casskop/blob/f59dbb9aeb316ee3a937d250367e5d2eb5b2f09e/docker/bootstrap/dgoss/util.sh#L117

https://github.com/Orange-OpenSource/casskop/blob/702c0a5dbd59f24511330c414f83d7ffc9e2d54a/pkg/controller/cassandracluster/generator.go#L137-L140

 There might be other information to refactor outside of the go source code in order to avoid having to change it at multiple place

**Comment by cscetbon** [comment]
@jsanda could such a refactoring be a problem to use casskop as a dependency  ?

**Comment by allamand** [comment]
The dogs script are used to test that the volumes behaves correctly in the code. What optimisation would you like to do here ?

**Comment by cscetbon** [comment]
As I said in the description, the same information is used at different place. Look at PR #184 to get an idea of what I'm talking about

**Comment by cscetbon** [comment]
We have in mind to automate the releasing process. We'll use it as an opportunity to refactor code and versioning.
