### ISSUE TITLE
Unused CassandraCluster fields

### ISSUE THREAD

**Issue by erdrix** [Orange-OpenSource/casskop#188]
# Bug Report

## What did you do

Since the introduction of OpenApiV3 validation with the PR https://github.com/Orange-OpenSource/casskop/pull/122, we deployed, for example the following CassandraCluster :  https://github.com/Orange-OpenSource/casskop/blob/master/test/e2e/testdata/cassandracluster-1DC-no-autopilot.yaml

## What did you expect to see?

The creation of CassandraCluster object.

## What did you see instead? Under which circumstances?

```log
error: error validating "test/e2e/testdata/cassandracluster-1DC.yaml": 
error validating data: [ValidationError(CassandraCluster.spec): 
unknown field "imagePullPolicy" in com.orange.db.v1alpha1.CassandraCluster.spec, 
ValidationError(CassandraCluster.spec): unknown field "rollingPartition" 
in com.orange.db.v1alpha1.CassandraCluster.spec]; 
if you choose to ignore these errors, turn validation off with --validate=false
```

## Environment 

- branch : master

## Possibile Solution

It seems the two fields `imagePullPolicy` and `rollingPartition` was not used or bad defined.

For the `imagePullPolicy` one, we only need to change the spec of cassandraCluster : https://github.com/Orange-OpenSource/casskop/blob/master/pkg/apis/db/v1alpha1/cassandracluster_types.go#L630, par : 

```go
//ImagePullPolicy define the pull policy for C* docker image
ImagePullPolicy v1.PullPolicy `json:"imagePullPolicy,omitempty"`
```

For the `rollingPartition` one, the field isn't defined at all, and so the usage isn't implemented. So we need to add the code which implemented the logic.

**Comment by cscetbon** [comment]
I think this issue has been fixed
