### ISSUE TITLE
How can I modify the CASSANDRA_MAX_HEAP

### ISSUE THREAD

**Issue by eramirez51** [Orange-OpenSource/casskop#219]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around casskop ?**

## Question

**What did you do?**

I wanted to modify the `Xms` and `Xmx` JVM options, so I supplied my `jvm.options` file expecting that it will be honored by casskop.

**What did you expect to see?**

My final jvm.options file should have my final Xms and Xmx settings.

**What did you see instead? Under which circumstances?**

Casskop has overridden my settings.

https://github.com/Orange-OpenSource/casskop/blob/a6747830f6e2e19ff5f26f142b18d1132fab2d7c/docker/bootstrap/files/run.sh#L101-L102

So it means my way of doing it is not correct.

In the documentation, it says `When there is no memory request, CassKop will limit it to "2048M".`.

How do I then tell CassKop to use my desired max heap?

Thanks for your answer

**Environment**
* casskop version:

` v0.5.2-release`

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: x509: certificate signed by unknown authority
```
* Kubernetes cluster kind: 

`v1.15.11-gke.3`

* Cassandra version:
`cassandra:3.11`
--

**Additional context**
Add any other context about the question here.

**Comment by cscetbon** [comment]
@eramirez51 We made the choice to not allow users to directly override that parameter. It's set by CassKop automatically to 2GB if you don't provide any resource limit, or a fourth of the memory limit set. You can find what it does below  https://github.com/Orange-OpenSource/casskop/blob/282d790d4c054d750ab058ddb600596355d20996/pkg/controller/cassandracluster/generator.go#L417-L424
to sum up, you should only worry about setting your limits properly. We usually set limits to requests https://github.com/Orange-OpenSource/casskop/blob/282d790d4c054d750ab058ddb600596355d20996/test/e2e/testdata/cassandracluster-1DC.yaml#L30

**Comment by hugeaim** [comment]
Thank you I got my answer. As I suspected, I am not using it correctly.
