### ISSUE TITLE
 0.5.2 the metrics sets seem to be very different now.

### ISSUE THREAD

**Issue by tengzhuofei** [Orange-OpenSource/casskop#221]
cassandra  3.11.6  
prometheus-operator-8.13.8

I need to  a dashbaord  . the metrics sets seem to be very different now.

**Comment by ahmedjami** [comment]
Hi @tengzhuofei 
You can use the new [BETA Dashboard](https://github.com/Orange-OpenSource/casskop/blob/monitoring/documentation/monitoring.md#install-our-dashboard) under monitoring branch,

Don't hesitate to test it, It will be merged soon on master branch once tested and approved :)

**Comment by tengzhuofei** [comment]
ok，This method solved my problem. I hope to be merged soon on master branch once tested and approved

**Comment by ahmedjami** [comment]
The new dashboard works well for you ? 
I would be interested to know if all the panels are displayed well and especially the Polystat panel :)

**Comment by cscetbon** [comment]
#224 has been merged. Closing the ticket now
