### ISSUE TITLE
External access

### ISSUE THREAD

**Issue by etimoshenko** [Orange-OpenSource/casskop#239]
Hi. How can I provide external access to cassandra by operator? I can't find solution in docs

**Comment by ahmedjami** [comment]
Hi @etimoshenko 

You are looking for access to Cassandra cluster from your application ? if it is running within the same k8s cluster as Cassandra, you can use the services exposed by casskop.
`k get svc` to list all services that exposed by casskop
External applications do not have this possibility, so you have to expose the service as LoadBalancer or Ingress...

More info at this blog post: http://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/

**Comment by etimoshenko** [comment]
Can you give me example, how can I expose cassandra for access outside a k8s cluster.
My problem, I can't start cassandra in hostnetwork by operator.
If add nodeport, this port not added to seeds.

**Comment by fdehay** [comment]
HI @etimoshenko,
What is you deployment environment? 
If you are on a public cloud, then you can use LoadBalancer
If on a private cluster, you need a Ingress Controller
More details are on the link provided by @ahmedjami 

We do not support hostNetwork or nodePort in CassKop as of now.
We can improve the examples in the documentation though :)
