### ISSUE TITLE
NodeSelector and Node taints support?

### ISSUE THREAD

**Issue by mizunos** [Orange-OpenSource/casskop#261]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around casskop ?**
Implement Node Selector and Node taints/pod tolerations - 
## Question

Need to be able to force cassandra cluster within a Node Pool on GKE.  I do not see anywhere in the doc on how to implement NodeSelector,  Tolerations

* Kubernetes version information:

K8s version 1.15

* Kubernetes cluster kind:  GKE

* Cassandra version: 3.11.7

**Comment by cscetbon** [comment]
@mizunos see [node-affinity](https://orange-opensource.github.io/casskop/docs/3_configuration_deployment/4_cluster_topology#node-affinity), [hard-antiaffinity](https://orange-opensource.github.io/casskop/docs/3_configuration_deployment/4_cluster_topology#configuring-hard-antiaffinity-in-cassandra-cluster) and [Taints](https://orange-opensource.github.io/casskop/docs/3_configuration_deployment/4_cluster_topology#using-dedicated-nodes)

**Comment by mizunos** [comment]
Thank you for the quick response - exactly what I need.
