### ISSUE TITLE
Default user name for a new Cassandra cluster

### ISSUE THREAD

**Issue by mizunos** [Orange-OpenSource/casskop#264]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around casskop ?**
General context of a new cassandra cluster - What is the first superuser account created in a new cluster

## Question

**What did you do?**
Follow the step by step and sucessfuly bring up a new dc1 cassandra cluster.  What is the default super user name and PW for the cluster using this method.   In a regular helm chart install w/o the operator,  once can specify what is the first account.  I do not see it in this scenario.  I see a secret created for a superuser but not sure where it is added 

**Environment**
* casskop version: 0.5.6 release

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.13", GitCommit:"039be162890396e3365ebcf824b3cf412b6f6cc4", GitTreeState:"clean", BuildDate:"2020-07-21T02:38:48Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
GKE
* Cassandra version:
3.11

**Additional context**
Add any other context about the question here.

**Comment by cscetbon** [comment]
@mizunos this is because we don’t use any cql statements on the new database created. It’s purely a default cassandra setting that you can alter by connecting using cql when the cluster is ready. The default login/password is cassandra/cassandra

**Comment by mizunos** [comment]
Thank you - got it. original secret works fine
