### ISSUE TITLE
no matches for kind "CassandraBackup" in version "db.orange.com/v1alpha1"

### ISSUE THREAD

**Issue by ThaSami** [Orange-OpenSource/casskop#272]
## Question

**What did you do?**
applying 
https://orange-opensource.github.io/casskop/docs/5_operations/3_5_backup_restore

**What did you expect to see?**
The resource to work

**What did you see instead? Under which circumstances?**
no matches for kind "CassandraBackup" in version "db.orange.com/v1alpha1"

**Environment**
* casskop version:
cassandra-operator-0.5.6

* Kubernetes version information:
  insert output of `kubectl version` here
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
CassandraBackup

* Cassandra version:
3.11

**Additional context**
how to get backup works? + the documentation there is not helpful at all. if u can provide an example to backup in local storage/gcp that would be great

**Comment by fdehay** [comment]
hello @ThaSami , the backup functionnalities are not yet merged, it should be anytime today.
It comes with Version 1.0.0.
You are testing 0.5.6
Sorry there is a little time delay betwwen the documentation and the code.
Regarding the documentation, the backup will not work with local storage, only gcp or s3.
I will tell you when you can get v1.0.0

**Comment by fdehay** [comment]
You can see the PR/ https://github.com/Orange-OpenSource/casskop/pull/269

**Comment by ThaSami** [comment]
@fdehay Thanks for answering. 
would deleting the old operator cause any issues to Cassandra Cluster when upgrading to v1.0.0?

**Comment by fdehay** [comment]
Hi @ThaSami, we have released V1 so you can change the image, no problem on the operator side.

**Comment by ThaSami** [comment]
Thanks @fdehay  
any plans to support local storage soon? as it is a very expensive process to take backups to the cloud both on bandwidth/cost

**Comment by cscetbon** [comment]
@ThaSami you can already use an s3 provider on your local cluster similar to Minio.

**Comment by ThaSami** [comment]
Cool, thank you.

**Comment by drkhosla** [comment]
I am using CentOS 8.2 and Kubernetes 1.19.3. While installing Casskop 1.0.0, I give following commands.

kubectl apply -f https://raw.githubusercontent.com/OrangeOpenSource/casskop/master/deploy/crds/db.orange.com_cassandraclusters_crd.yaml
helm install casskop --namespace=cassandra orange-incubator/cassandra-operator

Casskop pod give error CrashLoopBackOff and log show alternating two errors
time="2020-10-19T05:46:12Z" level=error msg="no matches for kind \"CassandraRestore\" in version \"db.orange.com/v1alpha1\"manager exited non-zero"

time="2020-10-19T05:46:34Z" level=error msg="no matches for kind \"CassandraBackup\" in version \"db.orange.com/v1alpha1\"manager exited non-zero"

I don't know how to resolve it

**Comment by cscetbon** [comment]
Sorry @drkhosla there are 2 news CRDs to install along that one and we need to add them to the documentation. You need to install all CRDS in https://github.com/Orange-OpenSource/casskop/tree/v1.0.0-release/deploy/crds/ (not the subdirectory)

**Comment by drkhosla** [comment]
> Sorry @drkhosla there are 2 news CRDs to install along that one and we need to add them to the documentation. You need to install all CRDS in https://github.com/Orange-OpenSource/casskop/tree/v1.0.0-release/deploy/crds/ (not the subdirectory)

Thanks now it is working after adding two other crds of backup and restore..

**Comment by chingandy** [comment]
@cscetbon Is it possible to provide an example for how to configure the backup definition with a minio local installation? I have been trying to figure this out for more than two days and still couldn't make it works. Thanks

> der on your local cluster
