### ISSUE TITLE
Invalid spec.container.image invalid image required

### ISSUE THREAD

**Issue by jemantheiy** [Orange-OpenSource/casskop#288]
## Bug Report

Version 1.0.1 of chart
Cassandra 3.11

Stood up the operator without a problem.  Using hostPath storage class on the cluster that is Kubernetes 1.15 version.  

Using the example v1 config map and the sample cluster except I define a topology with racks.  I have labels on all my k8s nodes and specify the rack topology in my cluster config.  

When I deploy the cluster, I get the statefulset generated but pods cannot generate due to the following exception:

invalid spec.container.image required exception.  

**Environment**
* casskop version: 1.01

* go version:

N/A

* Kubernetes version information:
1.15
Rancher/rke 
using local host path storage class.  

* Kubernetes cluster kind:  v1

* Cassandra version: 3.11

**Possible Solution**
Unknown, upgrade?  I did have to generate the crds manually by using the sample directory Kubernetes manifest.  

**Additional context**

**Comment by cscetbon** [comment]
Hey @jemantheiy, please provide the complete list  (GitHub links or gist) to the files you used. Showing what it creates in your kubernetes cluster would also help. (kubectl get cassandracluster xxx -o yaml, kubectl get statefulset xxx -o yaml, etc..)

**Comment by jemantheiy** [comment]
update: working on getting it, tried 1.0.2 and same results.

**Comment by cscetbon** [comment]
@jemantheiy any news ? I would vote to close this issue if you don't have a way to reproduce it.
