### ISSUE TITLE
Delete the crd problem of a cluster under 2 namespace In 2 clusters

### ISSUE THREAD

**Issue by tengzhuofei** [Orange-OpenSource/casskop#292]
## Bug Report
    I started 2 sets of cassandra clusters, but when I delete the crd of cassandraclusters.db.orange.com under one namespace, the pod under the other namespace is deleted.
**Environment**
* casskop version: 0.5.2

* go version: 1.13.4

* Kubernetes version information: 

* Kubernetes cluster kind: v1.15.6

* Cassandra version: 3.11.6

**Comment by fdehay** [comment]
hello @tengzhuofei,
It is normal behaviour: CRDs are clusterwide, if you delete the CRD itself, all cassandraclusters will be deleted on the K8S cluster regardless of the namespaces
Also, please use latest casskop version if possible
Regards
