### ISSUE TITLE
Enable cassandraBackups to create s3 buckets if needed

### ISSUE THREAD

**Issue by zachlipp** [Orange-OpenSource/casskop#299]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'm using a `CassandraBackup` that backs up to a `minio` s3 server within a cluster. If it's the first time this backup operation is performed, the bucket does not exist and the backup fails. 

**Describe the solution you'd like to see**
I'd like `CassandraBackupSpec` to add an optional field (e.g. `createMissingBucket`) that will create an s3 bucket if one does not exist.

Icarus accepts an argument for `createMissingBucket`; I think this feature could be implemented by populating this argument.

**Describe alternatives you've considered**
It's possible to create this bucket with an initContainer when the minio pod starts.

**Comment by cscetbon** [comment]
Hey @zachlipp, why not, do you feel you could provide a small PR with that change ? It shouldn't be too hard.

**Comment by zachlipp** [comment]
Awesome. Yeah, I'll take care of it.

**Comment by cscetbon** [comment]
@zachlipp do you need any guidance ?

**Comment by zachlipp** [comment]
@cscetbon I haven't quite started; I'll get to it in the next few days

**Comment by SuhailRahman** [comment]
Hi @cscetbon, I'm interested in making the changes, can you please guide me in doing so.

**Comment by cscetbon** [comment]
@SuhailRahman It should be as simple as adding the parameter mentioned to https://github.com/Orange-OpenSource/casskop/blob/e5f169582b5794493c1d431658236f0cc6c1ae9b/pkg/backrest/backrest.go#L105-L116 as you can see at https://github.com/instaclustr/instaclustr-icarus-go-client/blob/1f9f5e201fe23f965a92a2b3215f112c1edff16e/pkg/instaclustr_icarus/model_backup_operation_request.go#L43

**Comment by SuhailRahman** [comment]
I tried it out it works, but I'm observing that first-time backup fails and creates the bucket, the second time onwards backup works completely fine.

**Comment by smiklosovic** [comment]
Can you please tell me what exactly fails? I am little bit lost here. 

What I can do is to move this check / creation to coordinator (an Icarus instance contacted by operator as first when it is a global request) instead of having each individual Icarus doing the check but I am not sure if I am fixing the right thing here.

**Comment by smiklosovic** [comment]
Please check this one and let me know, it seems good here

gcr.io/cassandra-operator/instaclustr-icarus:1.0.10-SNAPSHOT-2

**Comment by smiklosovic** [comment]
@SuhailRahman does my latest comment fix your issue?

**Comment by SuhailRahman** [comment]
@smiklosovic I haven't tried it out, I'm little busy in another work. I'll try this tomorrow and let you know.

**Comment by SuhailRahman** [comment]
I tried it out and it works perfectly, thanks for the help!!

**Comment by smiklosovic** [comment]
I have pushed that change I did to Icarus' main brain but it is not released yet. You are free to use that image I pushed until then.

**Comment by cscetbon** [comment]
@SuhailRahman any news on that ? I suppose you need to upgrade the backrest image ?

**Comment by SuhailRahman** [comment]
@cscetbon are you referring to restoring tables?

**Comment by cscetbon** [comment]
@SuhailRahman no, this ticket only refers to the backup and the option to add. I'm asking what is the current status of that ticket

**Comment by SuhailRahman** [comment]
You can close this ticket.
