### ISSUE TITLE
Should system Auth Keyspace be altered for password authenication?

### ISSUE THREAD

**Issue by SuhailRahman** [Orange-OpenSource/casskop#320]
## Type of question

I was reading an article saying it is a best practice to change `system_auth` keyspace to `class: NetworkTopologyStrategy` when password authentication is enabled. I wanted to understand if there is a need to make these changes for a Cassandra Cluster of 3 racks? 

What I have observed from the current `system_auth` keyspace is that the `replication class is set to Simple` and the replication factor is 1. 
```
cassandra@cqlsh> describe system_auth;
CREATE KEYSPACE system_auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
```
```
kubectl get po -n cassandra-ns
cassandra-w0-dc1-rack1-0            2/2     Running           0          8m22s
cassandra-w0-dc1-rack2-0            2/2     PodInitializing   0         5m1s
cassandra-w0-dc1-rack3-0            2/2     PodInitializing           0          3m22s
```
Reference Link: https://cassandra.apache.org/doc/latest/operating/security.html#enabling-password-authentication

**Comment by cscetbon** [comment]
No changes on the database is done by the operator. If you want to change it, then you need to connect and make those changes or add a post run script on the node where you want to run it and ensure it's idempotent
