### ISSUE TITLE
add structural OpenAPI v3.0 validation schema to CassandraCluster CRD

### ISSUE THREAD

**Issue by allamand** [Orange-OpenSource/casskop#34]
CustomResources traditionally store arbitrary JSON (next to apiVersion, kind and metadata, which is validated by the API server implicitly). With OpenAPI v3.0 validation a schema can be specified, which is validated during creation and updates

With apiextensions.k8s.io/v1 the definition of a structural schema will be mandatory for CustomResourceDefinitions

reference : https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

**Comment by jsanda** [comment]
I can spend some time on this over the weekend.

**Comment by cscetbon** [comment]
It’s be great. Thanks @jsanda

**Comment by jsanda** [comment]
@cscetbon can this be closed?

**Comment by cscetbon** [comment]
Yes closing it, thanks
