### ISSUE TITLE
Upgrade to latest operator-sdk

### ISSUE THREAD

**Issue by cscetbon** [Orange-OpenSource/casskop#351]
## Feature Request
Our operator-sdk version is one year old. The goal of this ticket is to upgrade to the latest version.

**Comment by cscetbon** [comment]
@AKamyshnikova is it something you could work on ?

**Comment by AKamyshnikova** [comment]
Yes, sure, but I think it will be better to upgrade in series - like to v1.0.0 then to v1.x as some of version have breaking changes. I can make a serious of changes for this in a while.
