### ISSUE TITLE
Readiness probe timeouts for operator should be customizable via values.yaml

### ISSUE THREAD

**Issue by ajoskowski** [Orange-OpenSource/casskop#360]
## Feature Request
Hi Guys, we use casskop as Cassandra operator for our deployment stack on Azure.
We encountered on a problem that after upgrade of operator its deployment object cannot be marked as "ready".
There is a workaround: we have to increase "failureThreshold" timeout to value higher than 1s and everything works correctly - we are talking about this value: https://github.com/Orange-OpenSource/casskop/blob/master/helm/cassandra-operator/templates/deployment.yaml#L48
IMHO this value should be customizable via values.yaml file.

**Comment by fdehay** [comment]
Hi @ajoskowski,
Thanks for using Casskop and reporting your issue.
Orange is scaling down its effort on Casskop so it would be best if you could provide a PR for your request.
Good to know Casskop works on Azure :)
