### ISSUE TITLE
Custom Resource Spec property names and kube-openapi 

### ISSUE THREAD

**Issue by devdattakulkarni** [Orange-OpenSource/casskop#89]
Looking through the Custom Resource type definitions, I found following properties that may not be adhering to kube-openapi requirements.

CassandraClusterSpec.GCStdout
CassandraClusterSpec.UnlockNextOperation
PodLastOperation.Name
CassandraLastAction.Name
CassandraClusterStatus.SeedList
CPUAndMem.CPU
Topology.DC

Kube OpenAPI name validation rules expect the field name in Go code and field name in JSON to be exactly same with just the first letter in different case (Go code requires CamelCase, JSON requires camelCase).

Here are some other best practice guidelines around Operator development, packaging, documentation: https://github.com/cloud-ark/kubeplus/blob/master/Guidelines.md

**Comment by jsanda** [comment]
@devdattakulkarni thanks for point this out. I will address this in #87.
